version: '3'

services:
  nginx:
    build: ./server/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/code
    links:
      - web:web
    depends_on:
      - web
  web:
    build: ./app/
    command: bash -c "pipenv install; pipenv run gunicorn config.wsgi:application -w 2 -b :8000 --daemon; ./entry.sh"
    volumes:
      - ./app:/code
    expose:
      - "8000"
    depends_on:
      - "db"
    environment:
      - PULSE_TWITTER_CONSUMER_TOKEN 
      - PULSE_TWITTER_CONSUMER_SECRET
      - PULSE_TWITTER_ACCESS_TOKEN 
      - PULSE_TWITTER_ACCESS_TOKEN_SECRET
  db:
    image: postgres
volumes:
  mydata: