version: '3'

services:
  nginx:
    build: ./server/
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/code
    links:
      - web:web
    depends_on:
      - web
  web:
    build: ./app/
    command: bash -c "./entry.sh"
    volumes:
      - ./app:/code
    expose:
      - "8000"
    depends_on:
      - "db"
    environment:
      - PULSE_HOST_TYPE
      - PULSE_TWITTER_CONSUMER_TOKEN 
      - PULSE_TWITTER_CONSUMER_SECRET
      - PULSE_TWITTER_ACCESS_TOKEN 
      - PULSE_TWITTER_ACCESS_TOKEN_SECRET
      - PULSE_ADMIN_EMAIL_PASSWORD
      - HOST_IP
  db:
    image: postgres
volumes:
  mydata:
