# Generated by Django 2.1.5 on 2019-01-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyphrases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyphrase',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
