# Generated by Django 2.1.5 on 2019-01-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyphrases', '0003_auto_20190121_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyphrase',
            name='display',
            field=models.BooleanField(default=False, help_text='When checked, data is included in API responses.'),
        ),
        migrations.AlterField(
            model_name='keyphrase',
            name='active',
            field=models.BooleanField(default=True, help_text='When checked, data is collected about this keyphrase.'),
        ),
    ]
