# Generated by Django 2.1.5 on 2019-01-20 10:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('keyphrases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('keyphrase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='keyphrases.Keyphrase')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
