# Generated by Django 2.1.5 on 2019-01-20 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='data',
            new_name='payload',
        ),
    ]
