# Generated by Django 2.1.5 on 2019-01-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20190120_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='keyphrase',
        ),
        migrations.AddField(
            model_name='record',
            name='interval',
            field=models.PositiveIntegerField(default=0, help_text='The number of seconds in which data was recorded for this record.'),
            preserve_default=False,
        ),
    ]
